version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
